steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/ola-repo/ola-incentive-etl:$COMMIT_SHA', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/ola-repo/ola-incentive-etl:latest', '.']

  # 2. Push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/ola-repo/ola-incentive-etl:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/ola-repo/ola-incentive-etl:latest']

  # 3. Deploy or update Cloud Run Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'ola-incentive-etl-job'
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/ola-repo/ola-incentive-etl:latest'
      - '--region=asia-south1'
      - '--tasks=1'
      - '--max-retries=1'
      - '--task-timeout=15m'
      - '--memory=1Gi'
      - '--cpu=1'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ola-repo/ola-incentive-etl:$COMMIT_SHA'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ola-repo/ola-incentive-etl:latest'
